# Generated by Django 6.0.3 on 2026-07-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='📌', max_length=10)),
                ('icon_class', models.CharField(default='fas fa-project-diagram', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Aspects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='💡', max_length=10)),
                ('icon_class', models.CharField(default='fas fa-heart', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True, help_text='High-level overview of the project')),
                ('domain', models.CharField(choices=[('AI', '🤖 Artificial Intelligence'), ('ML', '📊 Machine Learning'), ('DL', '🧠 Deep Learning'), ('WEB', '🌐 Web Development'), ('DATA', '📈 Data Science'), ('MOBILE', '📱 Mobile Development'), ('CYBER', '🔒 Cybersecurity'), ('BLOCKCHAIN', '⛓️ Blockchain'), ('IOT', '🏠 Internet of Things'), ('GAME', '🎮 Game Development'), ('CLOUD', '☁️ Cloud Computing'), ('DEVOPS', '⚙️ DevOps'), ('FULLSTACK', '🚀 Full Stack'), ('DESKTOP', '🖥️ Desktop')], db_index=True, max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, '🟢 Very Easy'), (2, '🟡 Easy'), (3, '🟠 Medium'), (4, '🔴 Hard'), (5, '⚫ Very Hard')], default=3)),
                ('estimated_hours', models.IntegerField(blank=True, help_text='Total hours to complete', null=True)),
                ('estimated_weeks', models.IntegerField(blank=True, help_text='Weeks to complete (calculated from hours)', null=True)),
                ('team_size_recommended', models.IntegerField(default=1, help_text='Recommended team size (1-5)')),
                ('min_semester', models.IntegerField(default=3, help_text='Minimum recommended semester')),
                ('required_technologies', models.TextField(default='[]', help_text='JSON array of required technologies')),
                ('learning_outcomes', models.TextField(default='[]', help_text='JSON array of learning outcomes')),
                ('skill_gap_analysis', models.TextField(default='{}', help_text='JSON mapping of skills to learning time')),
                ('learning_roadmap', models.TextField(default='[]', help_text='JSON array of learning steps')),
                ('dataset_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('github_stars', models.IntegerField(default=0, help_text='GitHub stars count')),
                ('research_paper_url', models.URLField(blank=True, null=True)),
                ('youtube_tutorial', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('supervisor_approved', models.BooleanField(db_index=True, default=False)),
                ('supervisor_recommendation_count', models.IntegerField(default=0, help_text='How many times recommended by supervisors')),
                ('supervisor_approval_rate', models.FloatField(default=0.0, help_text='Percentage of approvals (0.0-1.0)')),
                ('popularity_score', models.IntegerField(db_index=True, default=0)),
                ('success_probability', models.FloatField(default=0.5, help_text='Project success rate (0.0-1.0)')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Historical completion rate (0-100)')),
                ('trending_score', models.FloatField(default=0.0, help_text='Trending calculation')),
                ('similarity_topics', models.TextField(default='[]', help_text='JSON array of similar project IDs')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('TRENDING', 'Trending')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Creator/Source', max_length=100)),
                ('aspects', models.ManyToManyField(blank=True, help_text='Project aspects: Frontend, Backend, Database, AI/ML, Deployment, etc.', related_name='projects', to='projects.aspect')),
                ('interests', models.ManyToManyField(blank=True, related_name='projects', to='projects.interest')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recommendations', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0.0, help_text='Percentage of students who accepted recommendation (0-100)')),
                ('average_feedback_score', models.FloatField(default=0.0)),
                ('trending_rank', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Analytics',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Overall match score (0-100)')),
                ('skill_match', models.FloatField(help_text='Skill matching score (0-100)')),
                ('interest_match', models.FloatField(help_text='Interest matching score (0-100)')),
                ('difficulty_match', models.FloatField(help_text='Difficulty suitability (0-100)')),
                ('time_feasibility', models.FloatField(default=100.0, help_text='Time availability match (0-100)')),
                ('gpu_factor', models.FloatField(default=1.0, help_text='GPU requirement factor')),
                ('aspect_coverage_score', models.FloatField(default=0.0, help_text='Score based on aspect coverage (0-100)')),
                ('supervisor_confidence_score', models.FloatField(default=0.0, help_text='Supervisor approval confidence (0-100)')),
                ('final_score', models.FloatField(default=0.0, help_text='Final combined recommendation score (0-100)')),
                ('confidence_level', models.CharField(choices=[('low', '🔴 Low Confidence'), ('medium', '🟡 Medium Confidence'), ('high', '🟢 High Confidence'), ('very_high', '✅ Very High Confidence')], default='medium', max_length=20)),
                ('skill_gaps', models.TextField(default='[]', help_text='JSON array of missing skills')),
                ('suggested_learning_path', models.TextField(default='[]', help_text='JSON array of learning steps')),
                ('match_reasons', models.TextField(default='[]', help_text='JSON array of why this project was recommended')),
                ('recommended_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_accepted', models.BooleanField(default=False)),
                ('was_viewed', models.BooleanField(default=False)),
                ('feedback_score', models.IntegerField(blank=True, help_text='User feedback rating (1-5)', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.project')),
            ],
            options={
                'ordering': ['-final_score', '-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', '💻 Programming Language'), ('frontend', '🎨 Frontend'), ('backend', '⚙️ Backend'), ('database', '📊 Database'), ('ai_ml', '🤖 AI/Machine Learning'), ('devops', '🚀 DevOps'), ('cloud', '☁️ Cloud'), ('data', '📈 Data Science'), ('security', '🔒 Security'), ('tools', '🛠️ Tools & Frameworks'), ('soft', '💡 Soft Skills')], default='tools', max_length=50)),
                ('proficiency_level', models.IntegerField(default=1, help_text='1=Beginner, 2=Intermediate, 3=Advanced, 4=Expert')),
                ('is_trending', models.BooleanField(default=False)),
                ('popularity_score', models.IntegerField(default=0)),
                ('icon_class', models.CharField(default='fas fa-code', max_length=50)),
            ],
            options={
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['category'], name='projects_sk_categor_08f551_idx'), models.Index(fields=['is_trending'], name='projects_sk_is_tren_b39dc7_idx')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='optional_skills',
            field=models.ManyToManyField(blank=True, help_text='Nice-to-have skills', related_name='optional_in_projects', to='projects.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_in_projects', to='projects.skill'),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_weeks', models.IntegerField(default=2)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('udemy_url', models.URLField(blank=True, null=True)),
                ('coursera_url', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_skills', to='projects.learningpath')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='projects.skill')),
            ],
            options={
                'ordering': ['skill'],
            },
        ),
        migrations.AddField(
            model_name='interest',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills typically related to this interest', to='projects.skill'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('semester', models.IntegerField(choices=[(1, '1th Semester'), (2, '2th Semester'), (3, '3th Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')], default=1)),
                ('cgpa', models.FloatField(blank=True, help_text='CGPA score (0-4.0)', null=True)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Electrical', 'Electrical Engineering'), ('Business', 'Business / Management'), ('Mechanical', 'Mechanical Engineering'), ('Other', 'Other / Interdisciplinary')], default='Computer Science', max_length=100)),
                ('time_available', models.IntegerField(choices=[(3, '3 months (Short)'), (6, '6 months (Medium)'), (9, '9 months (Long)'), (12, '12 months (Full semester)')], default=12, help_text='Months available for project')),
                ('has_gpu', models.BooleanField(default=False, help_text='Student has GPU access')),
                ('team_size', models.IntegerField(default=1, help_text='Team members (1-5)')),
                ('experience_level', models.CharField(choices=[('beginner', '🌟 Beginner - No coding experience'), ('intermediate', '📚 Intermediate - Know basics'), ('advanced', '🚀 Advanced - Ready for complex projects')], default='beginner', max_length=20)),
                ('ai_readiness_score', models.FloatField(default=0.0, help_text='AI/ML project readiness (0-100)')),
                ('learning_preference', models.CharField(choices=[('visual', 'Visual'), ('hands-on', 'Hands-on'), ('theoretical', 'Theoretical'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('past_project_ids', models.TextField(default='[]', help_text='JSON array of past project IDs')),
                ('preference_tags', models.TextField(default='[]', help_text='JSON array of preference tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_recommendation_date', models.DateTimeField(blank=True, null=True)),
                ('bookmarked_projects', models.ManyToManyField(blank=True, help_text='Favorite projects', related_name='bookmarked_by_students', to='projects.project')),
                ('interests', models.ManyToManyField(blank=True, related_name='students', to='projects.interest')),
                ('saved_projects', models.ManyToManyField(blank=True, related_name='saved_by_students', to='projects.project')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='projects.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filters_applied', models.TextField(default='{}', help_text='JSON of filters used')),
                ('total_shown', models.IntegerField(default=0)),
                ('recommendations', models.ManyToManyField(blank=True, to='projects.recommendation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='projects.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.student'),
        ),
        migrations.CreateModel(
            name='ProjectComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_as_first', to='projects.project')),
                ('project2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_as_second', to='projects.project')),
                ('winner_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='projects.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='projects.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['domain'], name='projects_pr_domain_9de146_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['difficulty'], name='projects_pr_difficu_b361ae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['supervisor_approved'], name='projects_pr_supervi_689eec_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['min_semester'], name='projects_pr_min_sem_7a91c8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='projects_st_email_9eb1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['semester'], name='projects_st_semeste_194a97_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['experience_level'], name='projects_st_experie_aec58e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['student', '-final_score'], name='projects_re_student_7be913_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['project', '-final_score'], name='projects_re_project_dfded1_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['confidence_level'], name='projects_re_confide_a48ebc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('student', 'project')},
        ),
    ]
